### ISSUE TITLE
Updating to core 2024.1.0b0 breaks integration

### ISSUE THREAD

**Issue by brucek1642** [uvjim/hass_hdhomerun#94]
Rolling back 2023.12.4 restores the functionality

Here are the logs

```
Invalid config
The following integrations and platforms could not be set up:

hdhomerun.binary_sensor ([Show logs](http://172.16.0.38:8123/config/logs?filter=hdhomerun.binary_sensor))
hdhomerun.select ([Show logs](http://172.16.0.38:8123/config/logs?filter=hdhomerun.select))
hdhomerun.sensor ([Show logs](http://172.16.0.38:8123/config/logs?filter=hdhomerun.sensor))
hdhomerun.update ([Show logs](http://172.16.0.38:8123/config/logs?filter=hdhomerun.update))
```

```
2023-12-27 19:10:22.131 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.hdhomerun.binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/hdhomerun/binary_sensor.py", line 56, in <module>
@dataclasses.dataclass
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2023-12-27 19:10:22.137 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'hdhomerun.binary_sensor': Platform not found (Exception importing custom_components.hdhomerun.binary_sensor).
2023-12-27 19:10:22.140 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.hdhomerun.select
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/hdhomerun/select.py", line 45, in <module>
@dataclasses.dataclass
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'custom_options' follows default argument
2023-12-27 19:10:22.142 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'hdhomerun.select': Platform not found (Exception importing custom_components.hdhomerun.select).
2023-12-27 19:10:22.145 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.hdhomerun.sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/hdhomerun/sensor.py", line 62, in <module>
@dataclasses.dataclass
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2023-12-27 19:10:22.153 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'hdhomerun.sensor': Platform not found (Exception importing custom_components.hdhomerun.sensor).
2023-12-27 19:10:22.155 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.hdhomerun.update
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/hdhomerun/update.py", line 41, in <module>
@dataclasses.dataclass
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2023-12-27 19:10:22.157 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'hdhomerun.update': Platform not found (Exception importing custom_components.hdhomerun.update).
2023-12-27 19:10:22.177 ERROR (MainThread) [homeassistant.components.button] Error while setting up hdhomerun platform for button
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/hdhomerun/button.py", line 82, in async_setup_entry
description=HDHomeRunButtonDescription(
^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: HDHomeRunButtonDescription.__init__() missing 1 required positional argument: 'press_action_arguments'
```

**Comment by uvjim** [comment]
I'll take a look when I can find some time. I'm guessing it's related to this

https://developers.home-assistant.io/blog/2023/12/11/entity-description-changes/

**Comment by townsmcp** [comment]
+1 for observing the same issue on 2024.1.0b2

**Comment by uvjim** [comment]
I've just pushed a beta that should address the issue.  I'm yet to test on any version that isn't the beta, but hopefully it'll all work - will check on my main system.

https://github.com/uvjim/hass_hdhomerun/tree/2023.12.1b0

**Comment by townsmcp** [comment]
Thank you @uvjim the update has worked

**Comment by brucek1642** [comment]
Thank you for all your efforts

I tested with core 2024.1.0b2 and on my live system with core 2023.12.4 and everything is working

**Comment by uvjim** [comment]
Fixed by https://github.com/uvjim/hass_hdhomerun/releases/tag/2024.1.1
