### ISSUE TITLE
No longer recognized or installable in HA

### ISSUE THREAD

**Issue by bmorgan99** [uvjim/hass_hdhomerun#97]
Home Assistant does not recognize it after the 2024.1.2 update,   I tried reinstalling and it is not found by discovery and adds no devices when the IP is manually entered.  It works fine from the app and web UI.  Getting this in the HA log:

```
Unable to prepare setup for platform 'hdhomerun.binary_sensor': Platform not found (Exception importing custom_components.hdhomerun.binary_sensor).
Unable to prepare setup for platform 'hdhomerun.button': Platform not found (Exception importing custom_components.hdhomerun.button).
Unable to prepare setup for platform 'hdhomerun.select': Platform not found (Exception importing custom_components.hdhomerun.select).
Unable to prepare setup for platform 'hdhomerun.sensor': Platform not found (Exception importing custom_components.hdhomerun.sensor).
Unable to prepare setup for platform 'hdhomerun.update': Platform not found (Exception importing custom_components.hdhomerun.update).
```

```
Hardware Model | HDFX-4K
Firmware Version | 20231214
ATSC3-DRM | SD20230420
Device ID | 10A2AF3E
MAC Address | 00:18:DD:0A:2A:F3
IP Address | 192.168.1.207
Subnet Mask | 255.255.255.0

HDHomeRun FLEX 4K
System Log
19700101-00:00:01 System: reset reason = power on
19700101-00:00:02 System: network link 100f
19700101-00:00:03 System: ip address obtained: [fe80::218:ddff:fe0a:2af3]/64
19700101-00:00:03 System: ip address obtained: 192.168.1.207/24
19700101-00:00:09 System: ip address obtained: [fd86:4c37:8379:e1b5:218:ddff:fe0a:2af3]/64
20240106-21:47:34 System: time changed from Thu Jan  1 00:00:20 1970 to Sat Jan  6 21:47:34 2024
20240106-21:47:36 System: ip address obtained: 169.254.159.137/16
20240106-21:48:59 Tuner: tuner0 tuning 106.1 WBRC (atsc3:515MHz-5005)
20240106-21:49:00 HTTP: rejecting request from [fd86:4c37:8379:e1b5:f86a:e922:eb68:85be] - protected channel
20240106-21:49:00 Tuner: tuner0 http stream ended (unknown reason)

\\homeassistant\config\custom_components
d----          12/29/2023  8:54 AM                __pycache__
d----          11/10/2022  3:02 AM                examples
d----          11/10/2022  3:02 AM                images
d----          11/28/2022  2:03 PM                pyhdhr
d----          11/10/2022  3:02 AM                translations
-----          11/10/2022  3:02 AM           9510 __init__.py
-----          11/10/2022  3:02 AM          10657 binary_sensor.py
-----          11/10/2022  3:02 AM           5906 button.py
-----          11/10/2022  3:02 AM          16382 config_flow.py
-----          11/10/2022  3:02 AM           2021 const.py
-----          11/10/2022  3:02 AM           1574 diagnostics.py
-----          11/10/2022  3:02 AM            108 hacs.json
-----          11/10/2022  3:02 AM            722 logger.py
-----          11/10/2022  3:02 AM            478 manifest.json
-----          11/10/2022  3:02 AM           4661 README.md
-----          11/10/2022  3:02 AM           3738 select.py
-----          11/10/2022  3:02 AM          12637 sensor.py
-----          11/10/2022  3:02 AM           3535 update.py

debugging on
2024-01-06 16:13:10.853 DEBUG (MainThread) [custom_components.hdhomerun] async_setup_entry (10A2AF3E) --> entered
2024-01-06 16:13:10.858 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> entered
2024-01-06 16:13:10.863 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> carrying out UDP discovery
2024-01-06 16:13:10.878 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> entered
2024-01-06 16:13:10.883 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> sending discovery packet: ('192.168.1.207', 65001), 0002000c0104000000010204ffffffff4e507f35
2024-01-06 16:13:10.888 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> exited
2024-01-06 16:13:11.125 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> waiting 1 second for responses
2024-01-06 16:13:11.648 ERROR (MainThread) [homeassistant.components.notify] Failed to initialize notification service webostv
2024-01-06 16:13:12.464 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> UDP discovery found 3 devices
2024-01-06 16:13:12.472 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> attempting to reach local discovery for 192.168.1.207
2024-01-06 16:13:12.497 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> attempting to reach local discovery for 192.168.1.207
2024-01-06 16:13:12.511 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> attempting to reach local discovery for 192.168.1.207
2024-01-06 16:13:12.919 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> discovered devices: [HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207]
2024-01-06 16:13:12.929 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> exited
2024-01-06 16:13:12.939 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_gather_details (192.168.1.207) --> entered
2024-01-06 16:13:12.948 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_gather_details (192.168.1.207) --> gathering details using UDP
2024-01-06 16:13:12.957 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> entered
2024-01-06 16:13:12.982 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> carrying out UDP discovery
2024-01-06 16:13:13.066 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> entered
2024-01-06 16:13:13.082 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> sending discovery packet: ('192.168.1.207', 65001), 0002000c0104000000010204ffffffff4e507f35
2024-01-06 16:13:13.091 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> exited
2024-01-06 16:13:13.136 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> waiting 1 second for responses
2024-01-06 16:13:14.471 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> UDP discovery found 3 devices
2024-01-06 16:13:14.482 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> discovered devices: [HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207]
2024-01-06 16:13:14.493 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> exited
2024-01-06 16:13:14.560 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /sys/version, value: None, timeout: 2.50
2024-01-06 16:13:14.569 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /sys/model, value: None, timeout: 2.50
2024-01-06 16:13:14.578 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /sys/hwmodel, value: None, timeout: 2.50
2024-01-06 16:13:14.671 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:14.804 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:14.966 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:15.009 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_gather_details (192.168.1.207) --> exited
2024-01-06 16:13:15.010 DEBUG (MainThread) [custom_components.hdhomerun] Finished fetching hdhomerun_10A2AF3E data in 4.157 seconds (success: True)
2024-01-06 16:13:15.022 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> entered
2024-01-06 16:13:15.034 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> carrying out UDP discovery
2024-01-06 16:13:15.050 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> entered
2024-01-06 16:13:15.063 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> sending discovery packet: ('192.168.1.207', 65001), 0002000c0104000000010204ffffffff4e507f35
2024-01-06 16:13:15.074 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> exited
2024-01-06 16:13:15.091 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> waiting 1 second for responses
2024-01-06 16:13:16.271 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> UDP discovery found 3 devices
2024-01-06 16:13:16.291 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> attempting to reach local discovery for 192.168.1.207
2024-01-06 16:13:16.472 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> attempting to reach local discovery for 192.168.1.207
2024-01-06 16:13:16.510 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> attempting to reach local discovery for 192.168.1.207
2024-01-06 16:13:16.549 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> discovered devices: [HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207]
2024-01-06 16:13:16.562 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> exited
2024-01-06 16:13:16.575 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_gather_details (192.168.1.207) --> entered
2024-01-06 16:13:16.588 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_gather_details (192.168.1.207) --> gathering details using UDP
2024-01-06 16:13:16.602 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> entered
2024-01-06 16:13:16.617 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> carrying out UDP discovery
2024-01-06 16:13:16.640 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> entered
2024-01-06 16:13:16.661 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> sending discovery packet: ('192.168.1.207', 65001), 0002000c0104000000010204ffffffff4e507f35
2024-01-06 16:13:16.679 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] _DiscoverProtocol.do_discover --> exited
2024-01-06 16:13:16.710 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> waiting 1 second for responses
2024-01-06 16:13:16.897 ERROR (MainThread) [reolink_aio.api] Host 192.168.1.23:443, could not verify a working RTSP url
2024-01-06 16:13:17.363 ERROR (MainThread) [reolink_aio.api] Host 192.168.1.30:443, could not verify a working RTSP url
2024-01-06 16:13:17.373 ERROR (MainThread) [reolink_aio.api] Host 192.168.1.23:443, could not verify a working RTSP url
2024-01-06 16:13:17.499 ERROR (Thread-10) [pychromecast.socket_client] [NvidiaShield(ed5b9f16-a2b7-e3f5-af73-867aa93b8c5a.local.):8009] Failed to connect to service ServiceInfo(type='mdns', data='SHIELD-Android-TV-ed5b9f16a2b7e3f5af73867aa93b8c5a._googlecast._tcp.local.'), retrying in 5.0s
2024-01-06 16:13:17.629 ERROR (MainThread) [reolink_aio.api] Host 192.168.1.30:443, could not verify a working RTSP url
2024-01-06 16:13:17.731 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> UDP discovery found 3 devices
2024-01-06 16:13:17.752 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> discovered devices: [HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207, HDHomeRunDevice 192.168.1.207]
2024-01-06 16:13:17.767 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.discover] async_discover --> exited
2024-01-06 16:13:17.781 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /sys/version, value: None, timeout: 2.50
2024-01-06 16:13:17.795 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /sys/model, value: None, timeout: 2.50
2024-01-06 16:13:17.808 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /sys/hwmodel, value: None, timeout: 2.50
2024-01-06 16:13:17.831 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:17.889 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:17.907 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:17.924 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_gather_details (192.168.1.207) --> exited
2024-01-06 16:13:17.938 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_refresh_tuner_status (192.168.1.207) --> entered
2024-01-06 16:13:17.951 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] async_refresh_tuner_status (192.168.1.207) --> refreshing tuner status using UDP
2024-01-06 16:13:17.964 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] _async_get_tuner_status_udp (192.168.1.207) --> entered
2024-01-06 16:13:17.978 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] _async_get_tuner_status_udp (192.168.1.207) --> querying all tuners
2024-01-06 16:13:17.992 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /tuner0/status, value: None, timeout: 2.50
2024-01-06 16:13:18.007 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /tuner1/status, value: None, timeout: 2.50
2024-01-06 16:13:18.020 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /tuner2/status, value: None, timeout: 2.50
2024-01-06 16:13:18.031 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> entered, tag: /tuner3/status, value: None, timeout: 2.50
2024-01-06 16:13:18.055 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:18.113 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:18.128 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:18.145 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.protocol] _get_set_req (192.168.1.207) --> exited
2024-01-06 16:13:18.161 DEBUG (MainThread) [custom_components.hdhomerun.pyhdhr.device] _async_get_tuner_status_udp (192.168.1.207) --> exited
2024-01-06 16:13:18.161 DEBUG (MainThread) [custom_components.hdhomerun] Finished fetching hdhomerun_tuner_status_10A2AF3E data in 3.151 seconds (success: True)
2024-01-06 16:13:18.175 DEBUG (MainThread) [custom_components.hdhomerun] async_setup_entry (10A2AF3E) --> setting up platforms: ['binary_sensor', 'button', 'select', 'sensor', 'update']
2024-01-06 16:13:18.177 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.hdhomerun.binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/hdhomerun/binary_sensor.py", line 56, in <module>
@dataclasses.dataclass
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2024-01-06 16:13:18.180 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'hdhomerun.binary_sensor': Platform not found (Exception importing custom_components.hdhomerun.binary_sensor).
2024-01-06 16:13:18.182 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.hdhomerun.button
```

**Comment by uvjim** [comment]
Have you ensured that you're running the latest version of this integration? This issue was fixed earlier this week in a release.

**Comment by bmorgan99** [comment]
I removed and reinstalled it today.

**Comment by uvjim** [comment]
The latest version of the integration is `2024.1.1`.
The number of entities will depend on your device.

**Comment by bmorgan99** [comment]
FYI: I plugged the custom repository url back into HACS and reinstalled it there, now all is well.  There must have been an issue with it before as I never got an update notification for the latest fix.
